"use client";

import { useState } from "react";
import { ArrowRight, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type HeroSectionProps = {
  onLaunch: (projectIdea: string) => void;
  isRunning: boolean;
  isComplete: boolean;
  source?: "live" | "backend" | null;
};

export function HeroSection({ onLaunch, isRunning, isComplete, source }: HeroSectionProps) {
  const [projectIdea, setProjectIdea] = useState("");

  const handleLaunch = () => {
    const trimmed = projectIdea.trim();
    if (!trimmed || isRunning) return;
    onLaunch(trimmed);
  };

  return (
    <section className="relative z-10 flex flex-col gap-6 px-4 py-8 sm:px-6 sm:py-10">
      <div className="max-w-2xl">
        <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-blueprint/25 bg-blueprint/5 px-3 py-1">
          <Sparkles className="size-3 text-blueprint" />
          <span className="font-mono text-[11px] tracking-wider text-blueprint uppercase">
            Autonomous company builder
          </span>
        </div>

        <h1 className="text-3xl font-semibold tracking-tight text-foreground sm:text-4xl lg:text-[2.75rem] lg:leading-[1.1]">
          Forge your next company
          <span className="block text-muted-foreground">
            with an AI engineering crew.
          </span>
        </h1>

        <p className="mt-4 max-w-xl text-sm leading-relaxed text-muted-foreground sm:text-base">
          Describe your vision. ForgeOS assembles a team of AI employees,
          orchestrates the build, and ships deliverables, like a vintage
          blueprint brought to life.
        </p>
      </div>

      <div className="max-w-2xl">
        <label htmlFor="project-input" className="sr-only">
          Project idea
        </label>
        <div className="relative rounded-lg border border-border/70 bg-card/60 p-1 shadow-sm backdrop-blur-sm">
          <div className="pointer-events-none absolute top-0 left-4 font-mono text-[9px] tracking-[0.2em] text-blueprint/60 uppercase">
            Project Brief, Rev. 001
          </div>
          <div className="mt-4 flex flex-col gap-2 sm:flex-row sm:items-center">
            <Input
              id="project-input"
              type="text"
              placeholder="e.g. A B2B analytics platform for renewable energy grids..."
              value={projectIdea}
              onChange={(e) => setProjectIdea(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && handleLaunch()}
              maxLength={2000}
              disabled={isRunning}
              className="h-11 flex-1 border-0 bg-transparent font-mono text-sm shadow-none focus-visible:ring-0 disabled:opacity-60"
            />
            <Button
              size="lg"
              onClick={handleLaunch}
              className="h-11 shrink-0 gap-2 bg-blueprint px-5 font-mono text-xs tracking-wide text-blueprint-foreground uppercase hover:bg-blueprint/90"
              disabled={!projectIdea.trim() || isRunning}
            >
              {isRunning ? "Launching..." : isComplete ? "Launched" : "Launch Company"}
              <ArrowRight className="size-4" />
            </Button>
          </div>
        </div>

        <p className="mt-3 font-mono text-[11px] text-muted-foreground">
          {isRunning
            ? source === "live"
              ? "Live orchestration in progress, streaming from ForgeOS via WebSocket."
              : source === "backend"
                ? "Live orchestration in progress, streaming from ForgeOS backend."
                : "Launching..."
            : isComplete
              ? "Workflow complete. Deliverables generated by ForgeOS crew."
              : "Click Launch Company to start the workflow."}
        </p>
      </div>
    </section>
  );
}
