import type { AIEmployee } from "@/lib/constants";
import type { MissionControlMessage } from "@/lib/mission-control-types";

export type EmployeeStatus = AIEmployee["status"];

export type ActivityEntry = {
  id: string;
  agent: string;
  action: string;
  time: string;
};

export type TimelineEvent = {
  id: string;
  phase: string;
  label: string;
  timestamp: string;
  status: "complete" | "active" | "pending";
};

export type Deliverable = {
  id: string;
  title: string;
  type: string;
  progress: number;
  /** Backend role that owns this deliverable, e.g. "Product Manager". */
  ownerRole?: string;
  /** Full markdown content when the artifact has been produced. */
  content?: string;
  /** Revision counter; 0 for first pass, 1+ after a rejection loop. */
  revision?: number;
  /** ISO timestamp of most recent artifact_produced event. */
  updatedAt?: string;
  /** Reviewer verdict on this artifact, if any review row exists. */
  approvalStatus?: "approved" | "rejected" | "pending" | "not_reviewed";
  /** Which role most recently reviewed it. */
  approvedBy?: string;
  /**
   * Streamed reasoning trace: the owning agent's "here's why I made that
   * decision" narration, accumulated from artifact_token events.
   */
  reasoningTrace?: string;
};

export type MemoryContext = {
  similarProjects: Array<{
    project: string;
    score: number;
    companyName?: string;
    technologies?: string[];
  }>;
  preferredTechnologies: Array<{ name: string; uses: number }>;
  pastMistakesCount: number;
  pastSecurityIssuesCount: number;
};

/**
 * A CEO-plan snapshot captured from the ``plan_created`` event. Used by the
 * Product Showcase to display the company brand, mission, and recommended
 * technology stack when the run completes.
 */
export type ProjectPlanSnapshot = {
  companyName?: string;
  mission?: string;
  vision?: string;
  recommendedStack?: string[];
  successMetrics?: string[];
  /**
   * Where the plan came from: "llm" when the AI provider generated it, or
   * "deterministic" when the backend fell back to built-in templates (AI
   * unavailable, credits exhausted, or no key configured). Lets the UI label
   * demo/fallback mode honestly.
   */
  planSource?: "llm" | "deterministic";
};

/** CEO's release summary, captured from the ``project_published`` event. */
export type ReleaseSummary = {
  text: string;
  timestamp: string;
};

/** A single starter file generated by the Engineer (LLM). */
export type GeneratedCodeFile = {
  path: string;
  language: string;
  content: string;
};

/**
 * The full code bundle emitted by the ``code_bundle_generated`` event. If
 * present, the Product Showcase prefers this over its own template-driven
 * files, so file contents are tailored to the specific project.
 */
export type GeneratedCodeBundle = {
  files: GeneratedCodeFile[];
  source: "llm" | "deterministic" | "hybrid";
};

/**
 * Per-agent time accounting used by the Intelligence Dashboard's
 * Agent Utilization row. ``activeMs`` sums time the agent spent in a
 * productive state (working, reviewing, waiting) between state
 * transitions. ``lastChangeAt`` is the wall-clock timestamp of the most
 * recent state transition, used to close the current interval when the
 * next transition arrives (or when the run finishes).
 */
export type AgentTimeAccount = {
  activeMs: number;
  lastStatus: string;
  lastChangeAt: string | null;
};

export type OrchestrationState = {
  isRunning: boolean;
  isComplete: boolean;
  progress: number;
  projectIdea: string;
  employees: AIEmployee[];
  activities: ActivityEntry[];
  timelineEvents: TimelineEvent[];
  deliverables: Deliverable[];
  missionControlMessages: MissionControlMessage[];
  /** Populated by the memory_seeded event at the start of every run. */
  memoryContext: MemoryContext | null;
  /** CEO plan snapshot, captured from plan_created. Null until then. */
  projectPlan: ProjectPlanSnapshot | null;
  /** CEO release summary, captured from project_published. Null until then. */
  releaseSummary: ReleaseSummary | null;
  /** Wall-clock timestamp when the run started, for elapsed time. */
  startedAt: string | null;
  /** Wall-clock timestamp when run_completed fired. */
  completedAt: string | null;
  /**
   * LLM-generated code bundle from the Engineer. Null when the LLM is off
   * or fails; the showcase falls back to template-generated files.
   */
  codeBundle: GeneratedCodeBundle | null;
  /**
   * Per-agent time accounting, keyed by backend role. Populated by the
   * ``agent_state_changed`` reducer. Used by the Intelligence Dashboard.
   */
  agentTime: Record<string, AgentTimeAccount>;
};
